### ISSUE TITLE
Simplify authentication mechanics

### ISSUE THREAD

**Issue by nbargnesi** [OpenBEL/openbel-api#100]
If we defer to clients like [OpenBEL/belmgr](https://github.com/OpenBEL/belmgr) to initiate their own authentication workflow it makes the server-side logic much simpler. The server shares a JWT secret with a token authority and uses it to verify the identity of the user providing the token. The downside is that the server itself can't tell the client how to authenticate. All it can do is verify them. The client is free to choose whichever strategy (provider) it chooses given the JWT secret is the same between server and provider.

This requires the client to have a JSON web token authority to authenticate with. The same authority will provide a token to the client it can relay to the server as a HTTP header. The server and authority share the secret used to encode and decode the JSON web token. When the server sees the token, it is decoded and verified, and the user is identified.
### Authentication enabled; new token

1: Client checks if authentication is enabled

``` http
GET /api/authentication-enabled
```

2: Server response shows authentication is enabled

``` json
{"enabled":true}
```

3: Client self-redirects to a JWT authority for authentication
4: Authority generates JWT token for client with the shared JWT secret
5: Authority redirects back to client with **new token**
6: Client uses new token in [HTTP authorization headers](https://en.wikipedia.org/wiki/Basic_access_authentication)

``` javascript
headers = {
  Authorization: 'Bearer ' + existingToken
};
```

5: Client continues with other workflows providing the `Authorization` header in each request
### Authentication enabled; existing token

1: Client checks if authentication is enabled

``` http
GET /api/authentication-enabled
```

2: Server response shows authentication is enabled

``` json
{"enabled":true}
```

3: Client checks for existing tokens (e.g., [local storage](https://developer.mozilla.org/en-US/docs/Web/API/Window/localStorage))
4: An **existing token is found** and is used in [HTTP authorization headers](https://en.wikipedia.org/wiki/Basic_access_authentication)

``` javascript
headers = {
  Authorization: 'Bearer ' + existingToken
};
```

5: Client continues with other workflows providing the `Authorization` header in each request
### Authentication disabled

1: Client checks if authentication is enabled

``` http
GET /api/authentication-enabled
```

2: Server response shows authentication **is disabled**

``` json
{"enabled":false}
```

3: Client continues with other workflows

**Comment by nbargnesi** [comment]
Looking for feedback @abargnesi and @wshayes

**Comment by wshayes** [comment]
This proposal looks really good.  It allows for the deployment of the OpenBEL ecosystem with different authentication endpoints based on the deployer's needs as long as they service the client's request for a token using the required protocol.  I should write up the protocol expected for the client side.

**Comment by abargnesi** [comment]
This approach looks good to me. Cleanly separates authentication provider configuration to the SPA which I think is a better fit.

**Comment by nbargnesi** [comment]
Okay, I'll make a PR out of it.
