### ISSUE TITLE
Validation of BEL 2.0 expression (fusion) fails

### ISSUE THREAD

**Issue by maestroe** [OpenBEL/openbel-api#132]
Examples taken from [BEL 2.0 specification](http://openbel.org/language/version_2.0/bel_specification_version_2.0.html)

Valid term 
`r(fus(HGNC:TMPRSS2, r.1_79, HGNC:ERG, r.312_5034))`
delivers following validation object:
```
{
    "validation": {
        "expression": "r(fus(HGNC:TMPRSS2, r.1_79, HGNC:ERG, r.312_5034))",
        "message": "Invalid syntax.",
        "term_signatures": [
            
        ],
        "valid_semantics": false,
        "valid_syntax": false,
        "warnings": [
            
        ]
    }
}
```

Tested with BEL 2.0 endpoint and API method "/api/expressions/{term}/validation".

**Comment by wshayes** [comment]
Fixed this in the documentation when I fixed the variant BEL2 documentation.

This validates:  r(fus(HGNC:TMPRSS2, "r.1_79", HGNC:ERG, "r.312_5034"))

**Comment by maestroe** [comment]
I can confirm that this validates!
