### ISSUE TITLE
 Validation of BEL 2.0 expression (rxn) fails

### ISSUE THREAD

**Issue by maestroe** [OpenBEL/openbel-api#134]
Examples taken from [BEL 2.0 specification](http://openbel.org/language/version_2.0/bel_specification_version_2.0.html)

Valid term 
`rxn(reactants(a(CHEBI:superoxide)),products(a(CHEBI:"hydrogen peroxide"), a(CHEBI:"oxygen"))`
delivers following validation object:
```
{
    "validation": {
        "expression": "rxn(reactants(a(CHEBI:superoxide)),products(a(CHEBI:\"hydrogen peroxide\"), a(CHEBI:\"oxygen\"))",
        "message": "Invalid syntax.",
        "term_signatures": [
            
        ],
        "valid_semantics": false,
        "valid_syntax": false,
        "warnings": [
            
        ]
    }
}
```

Tested with BEL 2.0 endpoint and API method "/api/expressions/{term}/validation".

**Comment by abargnesi** [comment]
This was a BEL syntax error in the specification. It was missing an closing parenthesis, after adding it the semantic validation was a success.
