### ISSUE TITLE
Components API is returning a wrong argument.

### ISSUE THREAD

**Issue by maestroe** [OpenBEL/openbel-api#138]
(Minor issue)

API is returning an incorrect response for one of the arguments for the statement `rxn(reactants(a(CHEBI:superoxide)),products(a(CHEBI:"hydrogen peroxide"), a(CHEBI:oxygen)))`.

The last argument is CHEBI:oxygen but the components API is returning CHEBI:"oxygen atom".

Why does the API or the parser changing an invalid concept name? Is it a feature, or a bug? If it is a feature, what if a curator wants to have an entity in a nanopub, which is missing in the current namespace?

**Comment by wshayes** [comment]
The API is changing 'oxygen' to a canonical form 'oxygen atom' in the CHEBI namespace. CHEBI doesn't have an entry for just oxygen (https://www.ebi.ac.uk/chebi/advancedSearchFT.do?searchString=oxygen&queryBean.stars=2)

Tony - can you add the particulars of how it does the re-mapping to the API docs?
