### ISSUE TITLE
Support document-level properties on evidence

### ISSUE THREAD

**Issue by nbargnesi** [OpenBEL/openbel-api#60]
With more and more data published in BEL from different sources, we'll need some way of handling the pieces of data normally captured as document-level properties.

E.g.:

```
##################################################################################
# Document Properties Section
SET DOCUMENT Name = "Comparative Toxicogenomics Database"
SET DOCUMENT Description = "Comparative Toxicogenomics Database. Jan., 2012"
SET DOCUMENT Version = "1.0"
SET DOCUMENT Copyright = "Comparative Toxicogenomics Database"
```

(see OpenBEL/belmgr-web#2 for @ncatlett's original issue)

**Comment by nbargnesi** [comment]
I propose using structured/free annotations for this. If we implement #51 and capture these properties as part of the evidence context, it becomes trivial to meet use cases like versioning and mixed copyrights.

With that solution, generating the latest version of evidence from a particular database export becomes a simple MapReduce operation.

**Comment by wshayes** [comment]
Added for BEL Nanopubs using metadata section tag.
