### ISSUE TITLE
support autocomplete for values that include spaces

### ISSUE THREAD

**Issue by ncatlett** [OpenBEL/openbel-api#65]
Many of the biological process and pathology terms contain spaces and do not work in the auto complete.
For example - 
bp(GOBP:DNA repair)
no autocomplete suggestions are provided until the 'r' is typed, and the suggestions are for completion of the 'r' only, e.g. bp(GOBP:DNA r().

**Comment by ncatlett** [comment]
Also need to support other non-alphanumeric characters like quotation marks.

**Comment by wshayes** [comment]
Fixed
