### ISSUE TITLE
Smarter autocomplete using BEL sematic information

### ISSUE THREAD

**Issue by ncatlett** [OpenBEL/openbel-api#66]
Ideally autocomplete could be smarter.

For example, given 'p(', the autocomplete suggestions should reflect only the allowable arguments to the proteinAbundance function, e.g., namespace prefixes for namespaces that include Protein Concepts (HGNC, MGI, RGD, SP, EGID, SFAM). (potentially nice to also include potential outer functions like 'kin(p(' as suggestions).

Similarly, given 'bp(', should limit suggestions to namespace prefixes for namespaces including Biological Process concepts (GOBP, MESHPP).

Given a protein activity function 'kin(', the suggestions should be limited to the compatible functions (complexAbundance and proteinAbundance).

**Comment by wshayes** [comment]
Delivered by Tony in semantic autocomplete feature
